apiVersion: v1
kind: Service
metadata:
  name: prom-mysql-service
  labels:
    app: prom-mysql
    release: kube-prometheus-stack
    self-monitor: 'true'
spec:
  selector:
    app: prom-mysql
  ports:
    - protocol: TCP
      port: 80
      name: prometheus
      targetPort: 8080
  type: LoadBalancer  # Use NodePort or ClusterIP based on your needs
