apiVersion: v1
kind: Service
metadata:
  name: prommysql-service
spec:
  selector:
    app: prommysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use NodePort or ClusterIP based on your needs
